# The Site Configuration
# Documentation: https://chirpy.cotes.page/posts/getting-started/

# -----------------------------------------------------------------------------
# Site Settings
# -----------------------------------------------------------------------------

title: Starlit Library
tagline: "이영정의 천체물리학 블로그"
description: "제가 공부한 것을 기록하고 저장하는 장소입니다^^"
url: "https://blackhole-LYJ.github.io"
baseurl: ""

author: "이영정(Lee Young Jeong)"
github:
  username: blackhole-LYJ

theme: jekyll-theme-chirpy
# remote_theme: cotes2020/jekyll-theme-chirpy

# -----------------------------------------------------------------------------
# Pagination
# -----------------------------------------------------------------------------

paginate: 10

# -----------------------------------------------------------------------------
# Plugins
# -----------------------------------------------------------------------------

plugins:
  # - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'

# -----------------------------------------------------------------------------
# Chirpy Specific Settings
# -----------------------------------------------------------------------------

avatar: /assets/img/starlit.jpg
  # If you want to use the local image you uploaded, you need to put it in assets/img and reference it here.
  # But I deleted assets/. I will recreate assets/img and put the user uploaded image there later.

# Timezone
timezone: Asia/Seoul

# Language
lang: ko-KR

# Toc
toc: true

# Comments
comments:
  provider: disqus
  disqus:
    shortname: astrolyj
